spring:
  application:
    name: blog
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode-true&characterEncoding-utf-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjw.blog.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.wjw.blog: debug
  file:
    name: log/blog.log


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql